run:
  modules-download-mode: vendor

skip-dirs:
  - vendor

linters:
  enable-all: false
  enable:
    # Default linters
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

    # Optional ones we want to include
    - golint
    - gosec
    - unconvert
    - gocyclo
    - goimports
    - maligned
    - unparam
    - nakedret
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - funlen

linters-settings:
  goimports:
    local-prefixes: github.com/calvin/grpc_spike
  misspell:
    local: US
    ignore-words:

  govet:
    check-shadowing: true

output:
  format: colored-line-number

issues:
  # TODO: reintroduce this rule
  # exclude-use-default: false
  max-same-issues: 0

  exclude:
    # TODO: remove this rule
    - \bexported \w+ (\S*['.]*)([a-zA-Z'.*]*) should have comment\b

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gochecknoglobals
        - goconst
        - gosec
        - unparam
